// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ArduinoDemo

#include "../ui.h"

void ui_ScreenSet_screen_init(void)
{
ui_ScreenSet = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenSet, lv_color_hex(0x112D4E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSetWifi = lv_btn_create(ui_ScreenSet);
lv_obj_set_width( ui_ButtonSetWifi, 271);
lv_obj_set_height( ui_ButtonSetWifi, 46);
lv_obj_set_x( ui_ButtonSetWifi, -2 );
lv_obj_set_y( ui_ButtonSetWifi, -48 );
lv_obj_set_align( ui_ButtonSetWifi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSetWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSetWifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonSetWifi, lv_color_hex(0x3F72AF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonSetWifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSetWifi = lv_label_create(ui_ButtonSetWifi);
lv_obj_set_width( ui_LabelSetWifi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSetWifi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSetWifi, -5 );
lv_obj_set_y( ui_LabelSetWifi, 1 );
lv_obj_set_align( ui_LabelSetWifi, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSetWifi,"Set Up Wifi");
lv_obj_set_style_text_color(ui_LabelSetWifi, lv_color_hex(0xDBE2EF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSetWifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSetWifi, &ui_font_FontPuHui20bp4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonAlarm = lv_btn_create(ui_ScreenSet);
lv_obj_set_width( ui_ButtonAlarm, 271);
lv_obj_set_height( ui_ButtonAlarm, 46);
lv_obj_set_x( ui_ButtonAlarm, -3 );
lv_obj_set_y( ui_ButtonAlarm, 11 );
lv_obj_set_align( ui_ButtonAlarm, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonAlarm, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonAlarm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonAlarm, lv_color_hex(0x3F72AF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonAlarm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelAlarm = lv_label_create(ui_ButtonAlarm);
lv_obj_set_width( ui_LabelAlarm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelAlarm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelAlarm, -1 );
lv_obj_set_y( ui_LabelAlarm, 0 );
lv_obj_set_align( ui_LabelAlarm, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelAlarm,"Alarm clock");
lv_obj_set_style_text_color(ui_LabelAlarm, lv_color_hex(0xDBE2EF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelAlarm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelAlarm, &ui_font_FontPuHui20bp4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonRetClock = lv_btn_create(ui_ScreenSet);
lv_obj_set_width( ui_ButtonRetClock, 30);
lv_obj_set_height( ui_ButtonRetClock, 26);
lv_obj_set_x( ui_ButtonRetClock, -141 );
lv_obj_set_y( ui_ButtonRetClock, -105 );
lv_obj_set_align( ui_ButtonRetClock, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonRetClock, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonRetClock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonRetClock, lv_color_hex(0x3F72AF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonRetClock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageRetClock = lv_img_create(ui_ButtonRetClock);
lv_img_set_src(ui_ImageRetClock, &ui_img_return_png);
lv_obj_set_width( ui_ImageRetClock, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageRetClock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageRetClock, -2 );
lv_obj_set_y( ui_ImageRetClock, 1 );
lv_obj_set_align( ui_ImageRetClock, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageRetClock, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageRetClock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageRetClock,30);
lv_obj_set_style_img_recolor(ui_ImageRetClock, lv_color_hex(0xDBE2EF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageRetClock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonFactory = lv_btn_create(ui_ScreenSet);
lv_obj_set_width( ui_ButtonFactory, 271);
lv_obj_set_height( ui_ButtonFactory, 46);
lv_obj_set_x( ui_ButtonFactory, -3 );
lv_obj_set_y( ui_ButtonFactory, 71 );
lv_obj_set_align( ui_ButtonFactory, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonFactory, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonFactory, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonFactory, lv_color_hex(0x3F72AF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonFactory, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelFactory = lv_label_create(ui_ButtonFactory);
lv_obj_set_width( ui_LabelFactory, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelFactory, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelFactory, -1 );
lv_obj_set_y( ui_LabelFactory, 0 );
lv_obj_set_align( ui_LabelFactory, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelFactory,"Factory Mode");
lv_obj_set_style_text_color(ui_LabelFactory, lv_color_hex(0xDBE2EF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelFactory, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelFactory, &ui_font_FontPuHui20bp4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ButtonSetWifi, ui_event_ButtonSetWifi, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonAlarm, ui_event_ButtonAlarm, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonRetClock, ui_event_ButtonRetClock, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonFactory, ui_event_ButtonFactory, LV_EVENT_ALL, NULL);

}
