// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ArduinoDemo

#include "../ui.h"

void ui_ScreenClock_screen_init(void)
{
ui_ScreenClock = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenClock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenClock, lv_color_hex(0x112D4E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenClock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelClock = lv_obj_create(ui_ScreenClock);
lv_obj_set_width( ui_PanelClock, 318);
lv_obj_set_height( ui_PanelClock, 68);
lv_obj_set_x( ui_PanelClock, -2 );
lv_obj_set_y( ui_PanelClock, -6 );
lv_obj_set_align( ui_PanelClock, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelClock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelClock, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelClock, lv_color_hex(0x3F72AF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelClock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelTime = lv_label_create(ui_PanelClock);
lv_obj_set_width( ui_LabelTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTime, -2 );
lv_obj_set_y( ui_LabelTime, 2 );
lv_obj_set_align( ui_LabelTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTime,"23:59:59");
lv_obj_set_style_text_color(ui_LabelTime, lv_color_hex(0xDBE2EF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelTime, &ui_font_FontNumber48bp4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageSet = lv_img_create(ui_ScreenClock);
lv_img_set_src(ui_ImageSet, &ui_img_settings_icon_png);
lv_obj_set_width( ui_ImageSet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageSet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageSet, 131 );
lv_obj_set_y( ui_ImageSet, -92 );
lv_obj_set_align( ui_ImageSet, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageSet, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageSet,220);

ui_Labelcalendar = lv_label_create(ui_ScreenClock);
lv_obj_set_width( ui_Labelcalendar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labelcalendar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labelcalendar, -81 );
lv_obj_set_y( ui_Labelcalendar, 79 );
lv_obj_set_align( ui_Labelcalendar, LV_ALIGN_CENTER );
lv_label_set_text(ui_Labelcalendar,"2023-09-04");
lv_obj_set_style_text_color(ui_Labelcalendar, lv_color_hex(0xDBE2EF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labelcalendar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labelcalendar, &ui_font_FontNumber28bp4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Labelweek = lv_label_create(ui_ScreenClock);
lv_obj_set_width( ui_Labelweek, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labelweek, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labelweek, 98 );
lv_obj_set_y( ui_Labelweek, 77 );
lv_obj_set_align( ui_Labelweek, LV_ALIGN_CENTER );
lv_label_set_text(ui_Labelweek,"Monday");
lv_obj_set_style_text_color(ui_Labelweek, lv_color_hex(0xDBE2EF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labelweek, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labelweek, &ui_font_FontNumber28bp4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Labelweather = lv_label_create(ui_ScreenClock);
lv_obj_set_width( ui_Labelweather, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labelweather, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labelweather, -30 );
lv_obj_set_y( ui_Labelweather, -99 );
lv_obj_set_align( ui_Labelweather, LV_ALIGN_CENTER );
lv_label_set_text(ui_Labelweather,"Clear");
lv_obj_set_style_text_color(ui_Labelweather, lv_color_hex(0xCCC3C3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labelweather, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labelweather, &ui_font_FontPuHui20bp4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Labeltemperature = lv_label_create(ui_ScreenClock);
lv_obj_set_width( ui_Labeltemperature, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Labeltemperature, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Labeltemperature, -61 );
lv_obj_set_y( ui_Labeltemperature, -68 );
lv_obj_set_align( ui_Labeltemperature, LV_ALIGN_CENTER );
lv_label_set_text(ui_Labeltemperature,"26℃");
lv_obj_set_style_text_color(ui_Labeltemperature, lv_color_hex(0xCCC3C3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labeltemperature, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Labeltemperature, &ui_font_FontPuHui20bp4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageCloudy = lv_img_create(ui_ScreenClock);
lv_img_set_src(ui_ImageCloudy, &ui_img_cloudy_png);
lv_obj_set_width( ui_ImageCloudy, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageCloudy, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageCloudy, -119 );
lv_obj_set_y( ui_ImageCloudy, -83 );
lv_obj_set_align( ui_ImageCloudy, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageCloudy, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageCloudy, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageCloudy,80);
lv_obj_set_style_img_recolor(ui_ImageCloudy, lv_color_hex(0xCCC3C3), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageCloudy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageRain = lv_img_create(ui_ScreenClock);
lv_img_set_src(ui_ImageRain, &ui_img_light_rain_png);
lv_obj_set_width( ui_ImageRain, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageRain, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageRain, -118 );
lv_obj_set_y( ui_ImageRain, -80 );
lv_obj_set_align( ui_ImageRain, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageRain, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageRain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageRain,80);
lv_obj_set_style_img_recolor(ui_ImageRain, lv_color_hex(0xCCC3C3), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageRain, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageSunny = lv_img_create(ui_ScreenClock);
lv_img_set_src(ui_ImageSunny, &ui_img_sunny_png);
lv_obj_set_width( ui_ImageSunny, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageSunny, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageSunny, -121 );
lv_obj_set_y( ui_ImageSunny, -85 );
lv_obj_set_align( ui_ImageSunny, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageSunny, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageSunny, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageSunny,80);
lv_obj_set_style_img_recolor(ui_ImageSunny, lv_color_hex(0xCCC3C3), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageSunny, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageSnow = lv_img_create(ui_ScreenClock);
lv_img_set_src(ui_ImageSnow, &ui_img_snow_png);
lv_obj_set_width( ui_ImageSnow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageSnow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageSnow, -118 );
lv_obj_set_y( ui_ImageSnow, -87 );
lv_obj_set_align( ui_ImageSnow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageSnow, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageSnow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageSnow,80);
lv_obj_set_style_img_recolor(ui_ImageSnow, lv_color_hex(0xCCC3C3), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageSnow, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageWifi = lv_img_create(ui_ScreenClock);
lv_img_set_src(ui_ImageWifi, &ui_img_wifi_png);
lv_obj_set_width( ui_ImageWifi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageWifi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageWifi, 76 );
lv_obj_set_y( ui_ImageWifi, -105 );
lv_obj_set_align( ui_ImageWifi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageWifi, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageWifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageWifi,30);
lv_obj_set_style_img_recolor(ui_ImageWifi, lv_color_hex(0xDBE2EF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageWifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageThunderstor = lv_img_create(ui_ScreenClock);
lv_img_set_src(ui_ImageThunderstor, &ui_img_thunderstorm_png);
lv_obj_set_width( ui_ImageThunderstor, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageThunderstor, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageThunderstor, -120 );
lv_obj_set_y( ui_ImageThunderstor, -85 );
lv_obj_set_align( ui_ImageThunderstor, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageThunderstor, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageThunderstor, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageThunderstor,80);
lv_obj_set_style_img_recolor(ui_ImageThunderstor, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageThunderstor, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageAtmosphere = lv_img_create(ui_ScreenClock);
lv_img_set_src(ui_ImageAtmosphere, &ui_img_atmosphere_png);
lv_obj_set_width( ui_ImageAtmosphere, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageAtmosphere, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageAtmosphere, -122 );
lv_obj_set_y( ui_ImageAtmosphere, -89 );
lv_obj_set_align( ui_ImageAtmosphere, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageAtmosphere, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageAtmosphere, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageAtmosphere,80);
lv_obj_set_style_img_recolor(ui_ImageAtmosphere, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageAtmosphere, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageDrizzle = lv_img_create(ui_ScreenClock);
lv_img_set_src(ui_ImageDrizzle, &ui_img_drizzle_png);
lv_obj_set_width( ui_ImageDrizzle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageDrizzle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageDrizzle, -122 );
lv_obj_set_y( ui_ImageDrizzle, -88 );
lv_obj_set_align( ui_ImageDrizzle, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageDrizzle, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageDrizzle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageDrizzle,90);
lv_obj_set_style_img_recolor(ui_ImageDrizzle, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageDrizzle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ImageSet, ui_event_ImageSet, LV_EVENT_ALL, NULL);

}
