FROM ubuntu:22.04

RUN dpkg --add-architecture i386 \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
    apt-utils \
    file \
    git python3 python3-pip python-is-python3 \
    make gcc g++ \
    cmake ninja-build \
    wget unzip ca-certificates \
    libc6:i386 \
    libstdc++6:i386 \
    libgcc-s1:i386 \
    zlib1g:i386 \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /work
