// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ArduinoDemo

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void handleFactoryAction(lv_event_t * e);
void handleAlarmConfirmation(lv_event_t * e);
void handleButtonAlarmEvent(lv_event_t * e);
void handleButtonSetWifiEvent(lv_event_t * e);
void handleButtonResetAction(lv_event_t * e);
void handleButtonReturnWifiAction(lv_event_t * e);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
