// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ArduinoDemo

#include "../ui.h"

void ui_ScreenWifiList_screen_init(void)
{
ui_ScreenWifiList = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenWifiList, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenWifiList, lv_color_hex(0x112D4E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenWifiList, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonRetSet = lv_btn_create(ui_ScreenWifiList);
lv_obj_set_width( ui_ButtonRetSet, 30);
lv_obj_set_height( ui_ButtonRetSet, 26);
lv_obj_set_x( ui_ButtonRetSet, -141 );
lv_obj_set_y( ui_ButtonRetSet, -105 );
lv_obj_set_align( ui_ButtonRetSet, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonRetSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonRetSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonRetSet, lv_color_hex(0x3F72AF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonRetSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageRetSet = lv_img_create(ui_ButtonRetSet);
lv_img_set_src(ui_ImageRetSet, &ui_img_return_png);
lv_obj_set_width( ui_ImageRetSet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageRetSet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageRetSet, -2 );
lv_obj_set_y( ui_ImageRetSet, 1 );
lv_obj_set_align( ui_ImageRetSet, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageRetSet, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageRetSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageRetSet,30);
lv_obj_set_style_img_recolor(ui_ImageRetSet, lv_color_hex(0xDBE2EF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageRetSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelWifiList = lv_label_create(ui_ScreenWifiList);
lv_obj_set_width( ui_LabelWifiList, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelWifiList, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelWifiList, -71 );
lv_obj_set_y( ui_LabelWifiList, -103 );
lv_obj_set_align( ui_LabelWifiList, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWifiList,"Wi-Fi List");
lv_obj_set_style_text_color(ui_LabelWifiList, lv_color_hex(0xDBE2EF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelWifiList, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelWifiList, &ui_font_FontPuHui20bp4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpinnerLoadWifi = lv_spinner_create(ui_ScreenWifiList,1000,90);
lv_obj_set_width( ui_SpinnerLoadWifi, 80);
lv_obj_set_height( ui_SpinnerLoadWifi, 80);
lv_obj_set_align( ui_SpinnerLoadWifi, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SpinnerLoadWifi, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_SpinnerLoadWifi, lv_color_hex(0x3F72AF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SpinnerLoadWifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SpinnerLoadWifi, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_SpinnerLoadWifi, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ButtonRetSet, ui_event_ButtonRetSet, LV_EVENT_ALL, NULL);

}
