FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ARG USERNAME=devuser

RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get install -y \
                wget git python2 libc6-i386 \
                make npm

# build files expect "python", but it gets installed as "python2".
# create symbolic link to fix this.
RUN ln -s /usr/bin/python2 /usr/bin/python

RUN useradd -m -s /bin/bash ${USERNAME}
