FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ARG USERNAME=devuser

RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get install -y \
                wget git python3 python-is-python3 libc6-i386 \
                make npm

RUN useradd -m -s /bin/bash ${USERNAME}
