// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ArduinoDemo

#ifndef _ARDUINODEMO_UI_H
#define _ARDUINODEMO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenClock
void ui_ScreenClock_screen_init(void);
extern lv_obj_t *ui_ScreenClock;
extern lv_obj_t *ui_PanelClock;
extern lv_obj_t *ui_LabelTime;
void ui_event_ImageSet( lv_event_t * e);
extern lv_obj_t *ui_ImageSet;
extern lv_obj_t *ui_Labelcalendar;
extern lv_obj_t *ui_Labelweek;
extern lv_obj_t *ui_Labelweather;
extern lv_obj_t *ui_Labeltemperature;
extern lv_obj_t *ui_ImageCloudy;
extern lv_obj_t *ui_ImageRain;
extern lv_obj_t *ui_ImageSunny;
extern lv_obj_t *ui_ImageSnow;
extern lv_obj_t *ui_ImageWifi;
extern lv_obj_t *ui_ImageThunderstor;
extern lv_obj_t *ui_ImageAtmosphere;
extern lv_obj_t *ui_ImageDrizzle;
// SCREEN: ui_ScreenSet
void ui_ScreenSet_screen_init(void);
extern lv_obj_t *ui_ScreenSet;
void ui_event_ButtonSetWifi( lv_event_t * e);
extern lv_obj_t *ui_ButtonSetWifi;
extern lv_obj_t *ui_LabelSetWifi;
void ui_event_ButtonAlarm( lv_event_t * e);
extern lv_obj_t *ui_ButtonAlarm;
extern lv_obj_t *ui_LabelAlarm;
void ui_event_ButtonRetClock( lv_event_t * e);
extern lv_obj_t *ui_ButtonRetClock;
extern lv_obj_t *ui_ImageRetClock;
void ui_event_ButtonFactory( lv_event_t * e);
extern lv_obj_t *ui_ButtonFactory;
extern lv_obj_t *ui_LabelFactory;
// SCREEN: ui_ScreenWifiList
void ui_ScreenWifiList_screen_init(void);
extern lv_obj_t *ui_ScreenWifiList;
void ui_event_ButtonRetSet( lv_event_t * e);
extern lv_obj_t *ui_ButtonRetSet;
extern lv_obj_t *ui_ImageRetSet;
extern lv_obj_t *ui_LabelWifiList;
extern lv_obj_t *ui_SpinnerLoadWifi;
// SCREEN: ui_ScreenPassword
void ui_ScreenPassword_screen_init(void);
extern lv_obj_t *ui_ScreenPassword;
extern lv_obj_t *ui_TextPassword;
void ui_event_KeyboardPassword( lv_event_t * e);
extern lv_obj_t *ui_KeyboardPassword;
void ui_event_ButtonRetWifi( lv_event_t * e);
extern lv_obj_t *ui_ButtonRetWifi;
extern lv_obj_t *ui_ImageRetWifi;
extern lv_obj_t *ui_SpinnerLoadPassword;
// SCREEN: ui_ScreenAla
void ui_ScreenAla_screen_init(void);
extern lv_obj_t *ui_ScreenAla;
extern lv_obj_t *ui_Rollerhour;
extern lv_obj_t *ui_Rollerminute;
extern lv_obj_t *ui_Rollersecond;
extern lv_obj_t *ui_Labelcolon1;
extern lv_obj_t *ui_Labelcolon2;
void ui_event_ButtonConfirm( lv_event_t * e);
extern lv_obj_t *ui_ButtonConfirm;
extern lv_obj_t *ui_LabelConfirm;
void ui_event_ButtonRetSet2( lv_event_t * e);
extern lv_obj_t *ui_ButtonRetSet2;
extern lv_obj_t *ui_ImageRetSet2;
extern lv_obj_t *ui_LabelHour;
extern lv_obj_t *ui_LabelHour1;
extern lv_obj_t *ui_LabelHour2;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_settings_icon_png);   // assets/settings_icon.png
LV_IMG_DECLARE( ui_img_cloudy_png);   // assets/阴.png
LV_IMG_DECLARE( ui_img_light_rain_png);   // assets/小雨.png
LV_IMG_DECLARE( ui_img_sunny_png);   // assets/晴.png
LV_IMG_DECLARE( ui_img_snow_png);   // assets/小雪.png
LV_IMG_DECLARE( ui_img_wifi_png);   // assets/WIFI.png
LV_IMG_DECLARE( ui_img_thunderstorm_png);   // assets/Thunderstorm.png
LV_IMG_DECLARE( ui_img_atmosphere_png);   // assets/atmosphere.png
LV_IMG_DECLARE( ui_img_drizzle_png);   // assets/drizzle.png
LV_IMG_DECLARE( ui_img_return_png);   // assets/返回键.png

LV_FONT_DECLARE( ui_font_AliShuHeTi16sbpp4);
LV_FONT_DECLARE( ui_font_FontNumber28bp4);
LV_FONT_DECLARE( ui_font_FontNumber36bp4);
LV_FONT_DECLARE( ui_font_FontNumber48bp4);
LV_FONT_DECLARE( ui_font_FontPuHui20bp4);

extern void handleAlarmConfirmation(lv_event_t * e);
extern void handleKeyboardEvent(lv_event_t *e);
extern void handleButtonAlarmEvent(lv_event_t * e);
extern void handleButtonSetWifiEvent(lv_event_t * e);
extern void handleButtonResetAction(lv_event_t * e);
extern void handleButtonReturnWifiAction(lv_event_t * e);
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif



#endif
