// we need to import this file twice, so don't use normal "header guards"
#if AS_IOR_STRUCT || AS_ENUM
/*
// Idea taken from:
// https://codereview.stackexchange.com/questions/237410/macro-to-generate-an-enum-and-an-array-of-strings/288415#288415
*/

// This file is intended to centralize the pin roles and their features:
// It will be used to generate the "enum" of roles, just as it was in new_pins.h before
// but at the same place we can now give the "htmlPinRoleNames", before defined in new_http.c
// and also is "one-stop-shopping" for 
//	the number of channels per role
//	"function" of a role (DHT, AIR, ...)
// 
// every entry is of the form 
//  	X( <enum id>,"<PinRoleName>",<# of channels>,<function> ),
//
// where function is defined as a bitstring, so each role can have all possible
// combination of functions 
// (e.g. a DHT11 will be assigned "7" (DHT & TEMP & HUM ~ 00000111 = 7)
//
// 00000001		DHT	--> 1
// 00000010		TEMP	--> 2
// 00000100		HUM 	--> 4
// 00001000		AIR 	--> 8
// 
// since it's meant as a replacement also for "typedef enum ioRole_e" from "new_pins.h",
// we need to place the descriptions here, too

// so start of the definitio of a role are the
// "iodetails", later used to automatically fill the documentation 
// just use the same as before in new_pins.h:
// typedef enum ioRole_e {
// 	//iodetail:{"name":"None",
// 	//iodetail:"title":"TODO",
// 	//iodetail:"descr":"Default pin role; this pin does nothing.",
// 	//iodetail:"enum":"IOR_None",
// 	//iodetail:"file":"new_pins.h",
// 	//iodetail:"driver":""}
// 	IOR_None,
// 	//iodetail:{"name":"Relay",
// 	//iodetail:"title":"TODO",
// 	//iodetail:"descr":"an active-high relay. This relay is closed when a logical 1 value is on linked channel",
// 	//iodetail:"enum":"IOR_Relay",
// 	//iodetail:"file":"new_pins.h",
// 	//iodetail:"driver":""}
// 	IOR_Relay,




// 2024/10/03: 
// initial list below is generated by some cripts from
// "typedef enum ioRole_e" (in "new_pins.h") and
// "const char* htmlPinRoleNames[]" (in "new_html.c")
//
// added are the number of channels for this role 
// taken from "PIN_IOR_NofChan(int test)" (in "new_html.c")
// and the new introduced "function" of the role (see above)

// todo: adjust code to autogenerate docs which reffers to 
// the typedef enum ioRole_e in new_pins.h to use the "documentation" here 


#if AS_IOR_STRUCT
#   define X( a, b , c , d ) {b , c , d}
#elif AS_ENUM
#   define X( a, b , c , d ) a
#endif
// START marker for "getcommands.js" script
//START_OF_IODETAILS
	//iodetail:{"name":"None",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Default pin role; this pin does nothing.",
	//iodetail:"enum":"IOR_None",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_None," ",1,0 ),
	//iodetail:{"name":"Relay",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"an active-high relay. This relay is closed when a logical 1 value is on linked channel",
	//iodetail:"enum":"IOR_Relay",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_Relay,"Rel",1,0 ),
	//iodetail:{"name":"Relay_n",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"(as Relay but pin logical value is inversed)",
	//iodetail:"enum":"IOR_Relay_n",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_Relay_n,"Rel_n",1,0 ),
	//iodetail:{"name":"Button",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"a typical button of Tuya device with active-low state (a button that connects IO pin to ground when pressed and also has a 10k or so pull up resistor)",
	//iodetail:"enum":"IOR_Button",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_Button,"Btn",2,0 ),
	//iodetail:{"name":"Button_n",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"as Button but pin logical value is inversed",
	//iodetail:"enum":"IOR_Button_n",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_Button_n,"Btn_n",2,0 ),
	//iodetail:{"name":"LED",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"an active-high LED. The internals of 'LED' are the same as of 'Relay'. Names are just separate to make it easier for users.",
	//iodetail:"enum":"IOR_LED",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_LED,"LED",1,0 ),
	//iodetail:{"name":"LED_n",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"(as Led but pin logical value is inversed)",
	//iodetail:"enum":"IOR_LED_n",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_LED_n,"LED_n",1,0 ),
	//iodetail:{"name":"PWM",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Pulse width modulation output for LED dimmers (with MQTT dimming support from Home Assistant). Remember to set related channel to correct color index, in the RGBCW order. For CW only lights, set only CW indices.",
	//iodetail:"enum":"IOR_PWM",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_PWM,"PWM",1,0 ),
	//iodetail:{"name":"LED_WIFI",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"special LED to indicate WLan connection state. LED states are following: LED on = client mode successfully connected to your Router. Half a second blink - connecting to your router, please wait (or connection problem). Fast blink (200ms) - open access point mode. In safe mode (after failed boots), LED might not work.",
	//iodetail:"enum":"IOR_LED_WIFI",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_LED_WIFI,"WifiLED",0,0 ),
	//iodetail:{"name":"LED_WIFI_n",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"As LED_WIFI, but with inversed logic.",
	//iodetail:"enum":"IOR_LED_WIFI_n",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_LED_WIFI_n,"WifiLED_n",0,0 ),
	//iodetail:{"name":"Button_ToggleAll",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"this button toggles all channels at once",
	//iodetail:"enum":"IOR_Button_ToggleAll",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_Button_ToggleAll,"Btn_Tgl_All",0,0 ),
	//iodetail:{"name":"Button_ToggleAll_n",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Button_ToggleAll as, but inversed logic of button",
	//iodetail:"enum":"IOR_Button_ToggleAll_n",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_Button_ToggleAll_n,"Btn_Tgl_All_n",0,0 ),
	//iodetail:{"name":"DigitalInput",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"this is a simple digital input pin, it sets the linked channel to current logical value on it, just like digitalRead( ) from Arduino. This input has a internal pull up resistor.",
	//iodetail:"enum":"IOR_DigitalInput",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_DigitalInput,"dInput",1,0 ),
	//iodetail:{"name":"DigitalInput_n",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"As DigitalInput as above, but inverted",
	//iodetail:"enum":"IOR_DigitalInput_n",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_DigitalInput_n,"dInput_n",1,0 ),
	//iodetail:{"name":"ToggleChannelOnToggle",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"this pin will toggle target channel when a value on this pin changes (with debouncing). you can connect simple two position switch here and swapping the switch will toggle target channel relay on or off",
	//iodetail:"enum":"IOR_ToggleChannelOnToggle",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_ToggleChannelOnToggle,"TglChanOnTgl",1,0 ),
	//iodetail:{"name":"DigitalInput_NoPup",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"As DigitalInput, but without internal programmable pullup resistor. This is used for, for example, XR809 water sensor and door sensor.",
	//iodetail:"enum":"IOR_DigitalInput_NoPup",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_DigitalInput_NoPup,"dInput_NoPullUp",1,0 ),
	//iodetail:{"name":"DigitalInput_NoPup_n",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"As DigitalInput_n, but without internal programmable pullup resistor",
	//iodetail:"enum":"IOR_DigitalInput_NoPup_n",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_DigitalInput_NoPup_n,"dInput_NoPullUp_n",1,0 ),
	// energy sensor
		//iodetail:{"name":"BL0937_SEL",
		//iodetail:"title":"TODO",
		//iodetail:"descr":"SEL pin for BL0937 energy measuring devices. Set all BL0937 pins to autostart BL0937 driver. Don't forget to calibrate it later.",
		//iodetail:"enum":"IOR_BL0937_SEL",
		//iodetail:"file":"new_pins.h",
		//iodetail:"driver":""}
	X( IOR_BL0937_SEL,"BL0937SEL",0,0 ),
	//iodetail:{"name":"BL0937_CF",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"CF pin for BL0937 energy measuring devices. Set all BL0937 pins to autostart BL0937 driver. Don't forget to calibrate it later.",
	//iodetail:"enum":"IOR_BL0937_CF",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_BL0937_CF,"BL0937CF",0,0 ),
	//iodetail:{"name":"BL0937_CF1",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"CF1 pin for BL0937 energy measuring devices. Set all BL0937 pins to autostart BL0937 driver. Don't forget to calibrate it later.",
	//iodetail:"enum":"IOR_BL0937_CF1",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_BL0937_CF1,"BL0937CF1",0,0 ),
	//iodetail:{"name":"ADC",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Analog to Digital converter converts voltage to channel value which is later published by MQTT and also can be used to trigger scriptable events",
	//iodetail:"enum":"IOR_ADC",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_ADC,"ADC",1,0 ),
	//iodetail:{"name":"SM2135_DAT",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"SM2135 DAT pin for SM2135 modified-I2C twowire LED driver, used in RGBCW lights. Set both required SM2135 pins to autostart the related driver. Don't forget to Map the colors order later, so colors are not mixed.",
	//iodetail:"enum":"IOR_SM2135_DAT",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_SM2135_DAT,"SM2135DAT",0,0 ),
	//iodetail:{"name":"SM2135_CLK",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"SM2135 CLK pin for SM2135 modified-I2C twowire LED driver, used in RGBCW lights. Set both required SM2135 pins to autostart the related driver. Don't forget to Map the colors order later, so colors are not mixed.",
	//iodetail:"enum":"IOR_SM2135_CLK",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_SM2135_CLK,"SM2135CLK",0,0 ),
	//iodetail:{"name":"BP5758D_DAT",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"BP5758D DAT pin for BP5758D modified-I2C twowire LED driver, used in RGBCW lights. Set both required BP5758D pins to autostart the related driver. Don't forget to Map the colors order later, so colors are not mixed.",
	//iodetail:"enum":"IOR_BP5758D_DAT",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_BP5758D_DAT,"BP5758D_DAT",0,0 ),
	//iodetail:{"name":"BP5758D_CLK",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"BP5758D CLK pin for BP5758D modified-I2C twowire LED driver, used in RGBCW lights. Set both required BP5758D pins to autostart the related driver. Don't forget to Map the colors order later, so colors are not mixed.",
	//iodetail:"enum":"IOR_BP5758D_CLK",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_BP5758D_CLK,"BP5758D_CLK",0,0 ),
	//iodetail:{"name":"BP1658CJ_DAT",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"BP1658CJ DAT pin for BP5758D modified-I2C twowire LED driver, used in RGBCW lights. Set both required BP1658CJ pins to autostart the related driver. Don't forget to Map the colors order later, so colors are not mixed.",
	//iodetail:"enum":"IOR_BP1658CJ_DAT",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_BP1658CJ_DAT,"BP1658CJ_DAT",0,0 ),
	//iodetail:{"name":"BP1658CJ_CLK",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"BP1658CJ CLK pin for BP5758D modified-I2C twowire LED driver, used in RGBCW lights. Set both required BP1658CJ pins to autostart the related driver. Don't forget to Map the colors order later, so colors are not mixed.",
	//iodetail:"enum":"IOR_BP1658CJ_CLK",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_BP1658CJ_CLK,"BP1658CJ_CLK",0,0 ),
	//iodetail:{"name":"PWM_n",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"as above, but percentage of duty is inversed. This might be useful for some special LED drivers that are using single PWM to choose between Cool white and Warm white (it also needs setting a special flag in General options)",
	//iodetail:"enum":"IOR_PWM_n",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_PWM_n,"PWM_n",1,0 ),
	//iodetail:{"name":"IRRecv",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"IR receiver for our IRLibrary port",
	//iodetail:"enum":"IOR_IRRecv",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_IRRecv,"IRRecv",0,0 ),
	//iodetail:{"name":"IRSend",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"IR sender for our IRLibrary port",
	//iodetail:"enum":"IOR_IRSend",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_IRSend,"IRSend",0,0 ),
	//iodetail:{"name":"Button_NextColor",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"for RGB strip with buttons; sets next predefined color. For a LED strip that has separate POWER and COLOR buttons.",
	//iodetail:"enum":"IOR_Button_NextColor",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_Button_NextColor,"Btn_NextColor",0,0 ),
	//iodetail:{"name":"Button_NextColor_n",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"As NextColor, but inversed button logic",
	//iodetail:"enum":"IOR_Button_NextColor_n",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_Button_NextColor_n,"Btn_NextColor_n",0,0 ),
	//iodetail:{"name":"Button_NextDimmer",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"for RGB strip with buttons; when hold, adjusts the brightness",
	//iodetail:"enum":"IOR_Button_NextDimmer",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_Button_NextDimmer,"Btn_NextDimmer",0,0 ),
	//iodetail:{"name":"Button_NextDimmer_n",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"As NextDimmer, but inversed button logic",
	//iodetail:"enum":"IOR_Button_NextDimmer_n",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_Button_NextDimmer_n,"Btn_NextDimmer_n",0,0 ),
	//iodetail:{"name":"AlwaysHigh",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"always outputs 1",
	//iodetail:"enum":"IOR_AlwaysHigh",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_AlwaysHigh,"AlwaysHigh",0,0 ),
	//iodetail:{"name":"AlwaysLow",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"always outputs 0",
	//iodetail:"enum":"IOR_AlwaysLow",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_AlwaysLow,"AlwaysLow",0,0 ),
	//iodetail:{"name":"UCS1912_DIN",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"WIP driver, write a post on Elektroda if you need it working",
	//iodetail:"enum":"IOR_UCS1912_DIN",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_UCS1912_DIN,"UCS1912_DIN",0,0 ),
	//iodetail:{"name":"SM16703P_DIN",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"WIP driver, write a post on Elektroda if you need it working",
	//iodetail:"enum":"IOR_SM16703P_DIN",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_SM16703P_DIN,"SM16703P_DIN",0,0 ),
	//iodetail:{"name":"Button_NextTemperature",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Button that automatically allows you to control temperature of your LED device",
	//iodetail:"enum":"IOR_Button_NextTemperature",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_Button_NextTemperature,"Btn_NextTemperature",0,0 ),
	//iodetail:{"name":"Button_NextTemperature_n",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Like Button_NextTemperature, but inversed button logic",
	//iodetail:"enum":"IOR_Button_NextTemperature_n",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_Button_NextTemperature_n,"Btn_NextTemperature_n",0,0 ),
	//iodetail:{"name":"Button_ScriptOnly",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"This button does nothing automatically, even the linked channel is not changed. Useful for scripts, but you can still also use any buttons for scripting.",
	//iodetail:"enum":"IOR_Button_ScriptOnly",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_Button_ScriptOnly,"Btn_ScriptOnly",0,0 ),
	//iodetail:{"name":"Button_ScriptOnly_n",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Like Button_ScriptOnly, but inversed logic",
	//iodetail:"enum":"IOR_Button_ScriptOnly_n",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_Button_ScriptOnly_n,"Btn_ScriptOnly_n",0,0 ),
	//iodetail:{"name":"DHT11",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"DHT11 data line. You can have multiple DHT sensors on your device. Related driver is automatically started. Results are saved in related channels to pin with that role (when editing pins, you get two textboxes to set channel indexes)",
	//iodetail:"enum":"IOR_DHT11",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_DHT11,"DHT11",2,1 ),
	//iodetail:{"name":"DHT12",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"DHT12 data line. You can have multiple DHT sensors on your device. Related driver is automatically started. Results are saved in related channels to pin with that role (when editing pins, you get two textboxes to set channel indexes)",
	//iodetail:"enum":"IOR_DHT12",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_DHT12,"DHT12",2,1 ),
	//iodetail:{"name":"DHT21",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"DHT21 data line. You can have multiple DHT sensors on your device. Related driver is automatically started. Results are saved in related channels to pin with that role (when editing pins, you get two textboxes to set channel indexes)",
	//iodetail:"enum":"IOR_DHT21",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_DHT21,"DHT21",2,1 ),
	//iodetail:{"name":"DHT22",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"DHT22 data line. You can have multiple DHT sensors on your device. Related driver is automatically started. Results are saved in related channels to pin with that role (when editing pins, you get two textboxes to set channel indexes)",
	//iodetail:"enum":"IOR_DHT22",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_DHT22,"DHT22",2,1 ),
	//iodetail:{"name":"CHT83XX_DAT",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"DAT pin of CHT83XX. Setting this pin role and saving will reveal two fields next to it. Set first field to 1 and second to 2. Those are related channel numbers to store temperature and humidity.",
	//iodetail:"enum":"IOR_CHT83XX_DAT",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_CHT83XX_DAT,"CHT83XX_SDA",2,6 ),
	//iodetail:{"name":"CHT83XX_CLK",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"CLK pin of CHT83XX sensor",
	//iodetail:"enum":"IOR_CHT83XX_CLK",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_CHT83XX_CLK,"CHT83XX_SCK",0,0 ),
	//iodetail:{"name":"SHT3X_DAT",
	//iodetail:"title":"TODO",	
	//iodetail:"descr":"Humidity/temperature sensor DATA pin. Driver will autostart if both required pins are set. See [SHT Sensor tutorial topic here](https://www.elektroda.com/rtvforum/topic3958369.html), also see [this sensor teardown](https://www.elektroda.com/rtvforum/topic3945688.html)",
	//iodetail:"enum":"IOR_SHT3X_DAT",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_SHT3X_DAT,"SHT3X_SDA",2,6 ),
	//iodetail:{"name":"SHT3X_CLK",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Humidity/temperature sensor CLOCK pin. Driver will autostart if both required pins are set. See [SHT Sensor tutorial topic here](https://www.elektroda.com/rtvforum/topic3958369.html), also see [this sensor teardown](https://www.elektroda.com/rtvforum/topic3945688.html)",
	//iodetail:"enum":"IOR_SHT3X_CLK",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_SHT3X_CLK,"SHT3X_SCK",0,0 ),
	//iodetail:{"name":"SOFT_SDA",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Generic software SDA pin for our more advanced, scriptable I2C driver. This allows you to even connect a I2C display to OBK.",
	//iodetail:"enum":"IOR_SOFT_SDA",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_SOFT_SDA,"SoftSDA",1,0 ),
	//iodetail:{"name":"SOFT_SCL",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Generic software SCL pin for our more advanced, scriptable I2C driver.",
	//iodetail:"enum":"IOR_SOFT_SCL",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_SOFT_SCL,"SoftSCL",1,0 ),
	//iodetail:{"name":"SM2235_DAT",
	//iodetail:"title":"TODO",	
	//iodetail:"descr":"It works for both SM2235 and SM2335. SM2235 DAT pin for SM2235 modified-I2C twowire LED driver, used in RGBCW lights. Set both required SM2235 pins to autostart the related driver. Don't forget to Map the colors order later, so colors are not mixed.",
	//iodetail:"enum":"IOR_SM2235_DAT",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_SM2235_DAT,"SM2235DAT",1,0 ),
	//iodetail:{"name":"SM2235_CLK",
	//iodetail:"title":"TODO",	
	//iodetail:"descr":"It works for both SM2235 and SM2335. SM2235 CLK pin for SM2235 modified-I2C twowire LED driver, used in RGBCW lights. Set both required SM2235 pins to autostart the related driver. Don't forget to Map the colors order later, so colors are not mixed.",
	//iodetail:"enum":"IOR_SM2235_CLK",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_SM2235_CLK,"SM2235CLK",1,0 ),
	//iodetail:{"name":"BridgeForward",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Motor/Relay bridge driver control signal. FORWARD direction.",
	//iodetail:"enum":"IOR_BridgeForward",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_BridgeForward,"BridgeFWD",1,0 ),
	//iodetail:{"name":"BridgeReverse",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Motor/Relay bridge driver control signal. REVERSE direction.",
	//iodetail:"enum":"IOR_BridgeReverse",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_BridgeReverse,"BridgeREV",1,0 ),
	//iodetail:{"name":"SmartButtonForLEDs",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"A single button that does all control for LED. Click it toggle power, hold to adjust brightness, double click for next color, triple click for next temperature",
	//iodetail:"enum":"IOR_SmartButtonForLEDs",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_SmartButtonForLEDs,"Btn_SmartLED",1,0 ),
	//iodetail:{"name":"SmartButtonForLEDs_n",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"As SmartButtonForLEDs, but inverted",
	//iodetail:"enum":"IOR_SmartButtonForLEDs_n",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_SmartButtonForLEDs_n,"Btn_SmartLED_n",1,0 ),
	//iodetail:{"name":"DoorSensorWithDeepSleep",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Setting this role will make DoorSensor driver autostart. DoorSensor will work like digital input, sending only its value on change. When there are no changes for some times, device will go into deep sleep to save battery. When a change occurs, device will wake up and report change. See [a door sensor example here](https://www.elektroda.com/rtvforum/topic3960149.html)",
	//iodetail:"enum":"IOR_DoorSensorWithDeepSleep",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_DoorSensorWithDeepSleep,"DoorSnsrWSleep",1,0 ),
	//iodetail:{"name":"DoorSensorWithDeepSleep_NoPup",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"As DoorSensorWithDeepSleep, but no pullup resistor",
	//iodetail:"enum":"IOR_DoorSensorWithDeepSleep_NoPup",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_DoorSensorWithDeepSleep_NoPup,"DoorSnsrWSleep_nPup",1,0 ),
	//iodetail:{"name":"BAT_ADC",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Like ADC, but for a Battery driver that does Battery measurement. See [battery driver topic here](https://www.elektroda.com/rtvforum/topic3959103.html)",
	//iodetail:"enum":"IOR_BAT_ADC",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_BAT_ADC,"BAT_ADC",1,0 ),
	//iodetail:{"name":"BAT_Relay",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Like Relay, but for a Battery driver that does Battery measurement. See [battery driver topic here](https://www.elektroda.com/rtvforum/topic3959103.html)",
	//iodetail:"enum":"IOR_BAT_Relay",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_BAT_Relay,"BAT_Relay",1,0 ),
	//iodetail:{"name":"TM1637_DIO",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"TM1637 LED display driver DIO pin. Setting all required TM1637 pins will autostart related driver",
	//iodetail:"enum":"IOR_TM1637_DIO",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_TM1637_DIO,"TM1637_DIO",1,0 ),
	//iodetail:{"name":"TM1637_CLK",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"TM1637 LED display driver CLK pin. Setting all required TM1637 pins will autostart related driver",
	//iodetail:"enum":"IOR_TM1637_CLK",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_TM1637_CLK,"TM1637_CLK",1,0 ),
	//iodetail:{"name":"BL0937_SEL_n",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Inverted SEL alternative for BL0937. Choose only one, either SEL or SEL_n. SEL_n may be needed in rare cases.",
	//iodetail:"enum":"IOR_BL0937_SEL_n",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_BL0937_SEL_n,"BL0937SEL_n",0,0 ),
	//iodetail:{"name":"DoorSensorWithDeepSleep_pd",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"As DoorSensorWithDeepSleep, but with pulldown resistor",
	//iodetail:"enum":"IOR_DoorSensorWithDeepSleep_pd",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_DoorSensorWithDeepSleep_pd,"DoorSnsrWSleep_pd",1,0 ),
	//iodetail:{"name":"SGP_CLK",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"SGP Quality Sensor Clock line. will autostart related driver",
	//iodetail:"enum":"IOR_SGP_CLK",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_SGP_CLK,"SGP_CLK",0,0 ),
	//iodetail:{"name":"SGP_DAT",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"SGP Quality Sensor Data line. will autostart related driver",
	//iodetail:"enum":"IOR_SGP_DAT",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_SGP_DAT,"SGP_DAT",2,8 ),
	//iodetail:{"name":"ADC_Button",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Single ADC with multiple buttons connected.d",
	//iodetail:"enum":"ADC_Button",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_ADC_Button,"ADC_Button",1,0 ),
	//iodetail:{"name":"GN6932_CLK",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"QQQ",
	//iodetail:"enum":"GN6932_CLK",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_GN6932_CLK,"GN6932_CLK",1,0 ),
	//iodetail:{"name":"GN6932_DAT",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"QQQ",
	//iodetail:"enum":"GN6932_DAT",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_GN6932_DAT,"GN6932_DAT",1,0 ),
	//iodetail:{"name":"GN6932_STB",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"QQQ",
	//iodetail:"enum":"GN6932_STB",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_GN6932_STB,"GN6932_STB",1,0 ),
	//iodetail:{"name":"TM1638_CLK",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"QQQ",
	//iodetail:"enum":"TM1638_CLK",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_TM1638_CLK,"TM1638_CLK",1,0 ),
	//iodetail:{"name":"TM1638_DAT",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"QQQ",
	//iodetail:"enum":"TM1638_DAT",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_TM1638_DAT,"TM1638_DAT",1,0 ),
	//iodetail:{"name":"TM1638_STB",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"QQQ",
	//iodetail:"enum":"TM1638_STB",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_TM1638_STB,"TM1638_STB",1,0 ),
	//iodetail:{"name":"BAT_Relay_n",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Like BAT_Relay, but inversed. See [battery driver topic here](https://www.elektroda.com/rtvforum/topic3959103.html)",
	//iodetail:"enum":"IOR_BAT_Relay_n",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_BAT_Relay_n,"BAT_Relay_n",1,0 ),
	//iodetail:{"name":"KP18058_CLK",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"QQQ",
	//iodetail:"enum":"KP18058_CLK",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_KP18058_CLK,"KP18058_CLK",1,0 ),
	//iodetail:{"name":"KP18058_DAT",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"QQQ",
	//iodetail:"enum":"KP18058_DAT",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_KP18058_DAT,"KP18058_DAT",1,0 ),
	//iodetail:{"name":"DS1820",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"vers simple OneWire Temp sensor DS1820",
	//iodetail:"enum":"DS1820_IO",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_DS1820_IO,"DS1820_IO",1,2 ),
	//iodetail:{"name":"Total_Options",
	//iodetail:"title":"TODO",
	//iodetail:"descr":"Current total number of available IOR roles",
	//iodetail:"enum":"IOR_Total_Options",
	//iodetail:"file":"new_pins.h",
	//iodetail:"driver":""}
	X( IOR_Total_Options,"error",1,0 ),
// END marker for "getcommands.js" script	
//END_OF_IODETAILS
#undef X

#endif // #if AS_IOR_STRUCT || AS_ENUM
