#ifndef USER_MBEDTLS_CONFIG_H
#define USER_MBEDTLS_CONFIG_H

#include "mbedtls/config.h"

#undef  MBEDTLS_MD5_C
#undef  MBEDTLS_CAMELLIA_C
#define MBEDTLS_SHA256_SMALLER
#undef  MBEDTLS_SSL_KEEP_PEER_CERTIFICATE
#undef  MBEDTLS_RIPEMD160_C
#undef  MBEDTLS_SHA512_C

// Plataform specific
#undef  MBEDTLS_FS_IO
#undef  MBEDTLS_NET_C
#undef  MBEDTLS_TIMING_C
#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_ENTROPY_HARDWARE_ALT
#define MBEDTLS_MEMORY_BUFFER_ALLOC_C  
// Modes
#define MBEDTLS_SSL_CLI_C  // Only client enabled
#undef  MBEDTLS_SSL_SRV_C
// Protos
#undef  MBEDTLS_SSL_PROTO_SSL3
#undef  MBEDTLS_SSL_PROTO_TLS1
#undef  MBEDTLS_SSL_PROTO_TLS1_1
#define MBEDTLS_SSL_PROTO_TLS1_2  // Only TLS1.2 enabled
#undef  MBEDTLS_SSL_PROTO_TLS1_3_EXPERIMENTAL
#undef  MBEDTLS_SSL_PROTO_DTLS

// MPI / BIGNUM options 
#define MBEDTLS_MPI_WINDOW_SIZE            1 
#define MBEDTLS_MPI_MAX_SIZE             512 
// ECP Options
#define MBEDTLS_ECP_WINDOW_SIZE            2 
// Content Lenght
#define MBEDTLS_SSL_MAX_CONTENT_LEN     4096

/*
#undef  MBEDTLS_SSL_KEEP_PEER_CERTIFICATE
#undef  MBEDTLS_SSL_SERVER_NAME_INDICATION
#undef  MBEDTLS_AES_ROM_TABLES
#define MBEDTLS_AES_FEWER_TABLES
#define MBEDTLS_CAMELLIA_SMALL_MEMORY
//675296
#undef  MBEDTLS_CIPHER_MODE_CBC  //???
//671424
#undef  MBEDTLS_CIPHER_NULL_CIPHER
#undef  MBEDTLS_ENABLE_WEAK_CIPHERSUITES
#define MBEDTLS_REMOVE_3DES_CIPHERSUITES
//671424
// Only SECP384R1 or CURVE25519 //
#undef  MBEDTLS_ECP_DP_SECP192R1_ENABLED
#undef  MBEDTLS_ECP_DP_SECP224R1_ENABLED
#undef  MBEDTLS_ECP_DP_SECP256R1_ENABLED
#define MBEDTLS_ECP_DP_SECP384R1_ENABLED // da para desativar?
#undef  MBEDTLS_ECP_DP_SECP521R1_ENABLED
#undef  MBEDTLS_ECP_DP_SECP192K1_ENABLED
#undef  MBEDTLS_ECP_DP_SECP224K1_ENABLED
#undef  MBEDTLS_ECP_DP_SECP256K1_ENABLED
#undef  MBEDTLS_ECP_DP_BP256R1_ENABLED
#undef  MBEDTLS_ECP_DP_BP384R1_ENABLED
#undef  MBEDTLS_ECP_DP_BP512R1_ENABLED
#define MBEDTLS_ECP_DP_CURVE25519_ENABLED //usar somente esta
#undef  MBEDTLS_ECP_DP_CURVE448_ENABLED
//667568
// Only ECDHE RSA //
#undef  MBEDTLS_KEY_EXCHANGE_PSK_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_DHE_PSK_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_RSA_PSK_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_RSA_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_DHE_RSA_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_ECDH_RSA_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED
//664192
#undef MBEDTLS_GENPRIME
//663296
#undef  MBEDTLS_PKCS1_V15 //???
#undef  MBEDTLS_PKCS1_V21 //???
//659488
// Define only on development //
#undef  MBEDTLS_SELF_TEST
#undef  MBEDTLS_SSL_ALL_ALERT_MESSAGES
#undef  MBEDTLS_SSL_RECORD_CHECKING
#undef  MBEDTLS_SSL_CONTEXT_SERIALIZATION
#undef  MBEDTLS_SSL_DEBUG_ALL
#undef  MBEDTLS_VERSION_FEATURES
#undef  MBEDTLS_CERTS_C
//657824
#undef  MBEDTLS_X509_RSASSA_PSS_SUPPORT
//657216
#undef  MBEDTLS_ARC4_C
//655872
#undef  MBEDTLS_BLOWFISH_C
//650752
#undef  MBEDTLS_CAMELLIA_C
//648352
#undef  MBEDTLS_ARIA_C
#undef  MBEDTLS_DES_C
#undef  MBEDTLS_CCM_C
#undef  MBEDTLS_MD2_C
#undef  MBEDTLS_MD4_C
#undef  MBEDTLS_MD5_C
//641504
#undef  MBEDTLS_DHM_C
#define MBEDTLS_ECDH_C  // Enable only ECDH
#undef  MBEDTLS_ECDSA_C
#undef MBEDTLS_ECJPAKE_C
//639664
#undef MBEDTLS_PEM_PARSE_C
#undef MBEDTLS_PEM_WRITE_C
//638848
#undef  MBEDTLS_SHA1_C
//635376
#undef MBEDTLS_DEBUG_C
// 622032


// Enabled Ciphers
#define MBEDTLS_SHA256_SMALLER
#define MBEDTLS_CHACHA20_C
#define MBEDTLS_CHACHAPOLY_C
#define MBEDTLS_POLY1305_C
#define MBEDTLS_RSA_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_AES_C  // Tentar desativar
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_GCM_C

#undef  MBEDTLS_SHA512_C
#undef  MBEDTLS_RIPEMD160_C
#define MBEDTLS_SHA512_NO_SHA384
#undef  MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_KEY_EXCHANGE
*/

#endif
