#ifndef USER_MBEDTLS_CONFIG_H
#define USER_MBEDTLS_CONFIG_H

#include "mbedtls/config.h"
// Plataform specific
#undef  MBEDTLS_FS_IO
#undef  MBEDTLS_NET_C
#undef  MBEDTLS_TIMING_C
#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_ENTROPY_HARDWARE_ALT
#define MBEDTLS_MEMORY_BUFFER_ALLOC_C
#define MBEDTLS_MPI_WINDOW_SIZE            1
#define MBEDTLS_MPI_MAX_SIZE             512
#define MBEDTLS_ECP_WINDOW_SIZE            2
#define MBEDTLS_SSL_MAX_CONTENT_LEN     4096

// Modes
#define MBEDTLS_SSL_CLI_C  // Only client enabled
#undef  MBEDTLS_SSL_SRV_C 

// Protos
#undef  MBEDTLS_SSL_PROTO_SSL3
#undef  MBEDTLS_SSL_PROTO_TLS1
#undef  MBEDTLS_SSL_PROTO_TLS1_1
#define MBEDTLS_SSL_PROTO_TLS1_2  // Only TLS1.2 enabled
#undef  MBEDTLS_SSL_PROTO_TLS1_3_EXPERIMENTAL
#undef  MBEDTLS_SSL_PROTO_DTLS

// Enabled Ciphers
#define MBEDTLS_RSA_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_SHA256_SMALLER
#define MBEDTLS_AES_C
#undef  MBEDTLS_AES_ROM_TABLES
#define MBEDTLS_AES_FEWER_TABLES
#define MBEDTLS_ENTROPY_FORCE_SHA256

//Disabled ciphers
#undef  MBEDTLS_ARC4_C
#undef  MBEDTLS_BLOWFISH_C
#undef  MBEDTLS_CAMELLIA_C
#undef  MBEDTLS_ARIA_C
#undef  MBEDTLS_DES_C
#undef  MBEDTLS_CCM_C
#undef  MBEDTLS_MD2_C
#undef  MBEDTLS_MD4_C
#undef  MBEDTLS_MD5_C
#undef  MBEDTLS_RIPEMD160_C
#undef  MBEDTLS_SHA1_C
#undef  MBEDTLS_SHA512_C
#undef  MBEDTLS_CHACHA20_C
#undef  MBEDTLS_CHACHAPOLY_C
#undef  MBEDTLS_POLY1305_C
#undef  MBEDTLS_CIPHER_NULL_CIPHER
#undef  MBEDTLS_ENABLE_WEAK_CIPHERSUITES
#define MBEDTLS_REMOVE_3DES_CIPHERSUITES
#define MBEDTLS_CAMELLIA_SMALL_MEMORY
#undef  MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_KEY_EXCHANGE

// Curves //
#undef  MBEDTLS_ECP_DP_SECP192R1_ENABLED
#undef  MBEDTLS_ECP_DP_SECP224R1_ENABLED
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED  //Only SECP256R1
#undef  MBEDTLS_ECP_DP_SECP384R1_ENABLED
#undef  MBEDTLS_ECP_DP_SECP521R1_ENABLED
#undef  MBEDTLS_ECP_DP_SECP192K1_ENABLED
#undef  MBEDTLS_ECP_DP_SECP224K1_ENABLED
#undef  MBEDTLS_ECP_DP_SECP256K1_ENABLED
#undef  MBEDTLS_ECP_DP_BP256R1_ENABLED
#undef  MBEDTLS_ECP_DP_BP384R1_ENABLED
#undef  MBEDTLS_ECP_DP_BP512R1_ENABLED
#undef  MBEDTLS_ECP_DP_CURVE25519_ENABLED
#undef  MBEDTLS_ECP_DP_CURVE448_ENABLED

// Block mode
#define MBEDTLS_GCM_C              //Only GCM
#undef  MBEDTLS_CIPHER_MODE_CBC
#undef  MBEDTLS_CIPHER_MODE_CFB
#undef  MBEDTLS_CIPHER_MODE_CTR
#undef  MBEDTLS_CIPHER_MODE_OFB
#undef  MBEDTLS_CIPHER_MODE_XTS

// Exchange Key //
#define MBEDTLS_DHM_C
#define MBEDTLS_ECDH_C
#undef  MBEDTLS_ECDSA_C
#undef  MBEDTLS_ECJPAKE_C
#undef  MBEDTLS_KEY_EXCHANGE_PSK_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_DHE_PSK_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_RSA_PSK_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_RSA_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_DHE_RSA_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_ECDH_RSA_ENABLED
#undef  MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED

// Define only on development //
#undef  MBEDTLS_SELF_TEST
#undef  MBEDTLS_SSL_ALL_ALERT_MESSAGES
#undef  MBEDTLS_SSL_RECORD_CHECKING
#undef  MBEDTLS_SSL_CONTEXT_SERIALIZATION
#undef  MBEDTLS_SSL_DEBUG_ALL
#undef  MBEDTLS_VERSION_FEATURES
#undef  MBEDTLS_CERTS_C
#undef  MBEDTLS_DEBUG_C

/*
Avaliar efeito

#undef MBEDTLS_GENPRIME

#undef  MBEDTLS_PKCS1_V15
#undef  MBEDTLS_PKCS1_V21

#undef  MBEDTLS_X509_RSASSA_PSS_SUPPORT

#undef MBEDTLS_PEM_PARSE_C
#undef MBEDTLS_PEM_WRITE_C

APN

*/

#endif